'use strict';
module.exports = {};
var Bot = module.exports.Bot = require('./lib/Bot.js'),
    User = module.exports.User = require('./lib/User.js'),
    Chat = module.exports.Chat = require('./lib/Chat.js'),
    Message = module.exports.Message = require('./lib/Message.js'),
    PhotoSize = module.exports.PhotoSize = require('./lib/PhotoSize.js'),
    File = module.exports.File = require('./lib/File.js'),
    InlineQuery = module.exports.InlineQuery = require('./lib/InlineQuery.js'),
    ChosenInlineResult = module.exports.ChosenInlineResult = require('./lib/ChosenInlineResult.js'),
    Keyboard = module.exports.Keyboard = require('./lib/Keyboard.js'),
    ChatMember = module.exports.ChatMember = require('./lib/ChatMember.js'),
    UserProfilePhotos = module.exports.UserProfilePhotos = require ('./lib/UserProfilePhotos.js'),
    InlineQueryResultArticle = module.exports.InlineQueryResultArticle = require('./lib/InlineQueryResultArticle.js'),
    InlineQueryResultLocation = module.exports.InlineQueryResultLocation = require('./lib/InlineQueryResultLocation.js'),
    InlineQueryResultPhoto = module.exports.InlineQueryResultPhoto = require('./lib/InlineQueryResultPhoto.js'),
    InlineQueryResultGif = module.exports.InlineQueryResultGif = require('./lib/InlineQueryResultGif.js'),
    InlineQueryResultMpeg4Gif = module.exports.InlineQueryResultMpeg4Gif = require('./lib/InlineQueryResultMpeg4Gif.js'),
    InlineQueryResultVideo = module.exports.InlineQueryResultVideo = require('./lib/InlineQueryResultVideo.js'),
    InlineQueryResultAudio = module.exports.InlineQueryResultAudio = require('./lib/InlineQueryResultAudio.js'),
    InlineQueryResultVoice = module.exports.InlineQueryResultVoice = require('./lib/InlineQueryResultVoice.js'),
    InlineQueryResultDocument = module.exports.InlineQueryResultDocument = require('./lib/InlineQueryResultDocument.js'),
    InlineQueryResultVenue = module.exports.InlineQueryResultVenue = require('./lib/InlineQueryResultVenue.js'),
    InlineQueryResultContact = module.exports.InlineQueryResultContact = require('./lib/InlineQueryResultContact.js');